version: '3.8'

services:
  # Main application
  book-discovery-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: book-discovery-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AI_PROVIDER=openai
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - book-discovery-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama service for local AI
  ollama:
    image: ollama/ollama:latest
    container_name: book-discovery-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - book-discovery-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Development service with Ollama
  book-discovery-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: book-discovery-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - AI_PROVIDER=ollama
      - AI_BASE_URL=http://ollama:11434
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - ollama
    networks:
      - book-discovery-network
    profiles:
      - development

volumes:
  ollama_data:
    driver: local

networks:
  book-discovery-network:
    driver: bridge